import { defaultVisualTemplateModel } from "./model";

export const visualTemplateCategories = ["All", "Basic", "Document", "DITA", "Newsletter", "Social Media"];

export function getCreateVisualTemplateOptions() {
  return [
    {
      id: "blank",
      name: "Blank",
      description: "Start from scratch with an empty canvas.",
      category: "Basic",
      source: "blank",
      available: true,
      regions: [],
      preview: "blank",
    },
    {
      id: "basic",
      name: "Basic",
      description: "Hero, Body, Sidebar and Footer containers.",
      category: "Basic",
      source: "starter",
      available: true,
      regions: defaultVisualTemplateModel.regions,
      preview: "basic",
      badge: "Starter",
    },
    {
      id: "article",
      name: "Article",
      description: "Single-column article with title and body.",
      category: "Document",
      source: "planned",
      available: false,
      preview: "article",
    },
    {
      id: "two-column",
      name: "Two Column",
      description: "Split layout for side-by-side content.",
      category: "Document",
      source: "planned",
      available: false,
      preview: "two-column",
    },
    {
      id: "cover-page",
      name: "Cover Page",
      description: "Title page with centered content and footer.",
      category: "Document",
      source: "planned",
      available: false,
      preview: "cover",
    },
    {
      id: "reference",
      name: "Reference",
      description: "Structured reference topic with table rows.",
      category: "DITA",
      source: "planned",
      available: false,
      preview: "reference",
      badge: "DITA",
    },
    {
      id: "task",
      name: "Task",
      description: "Step-by-step task topic layout.",
      category: "DITA",
      source: "planned",
      available: false,
      preview: "task",
      badge: "DITA",
    },
    {
      id: "concept",
      name: "Concept",
      description: "Concept topic with icon and description.",
      category: "DITA",
      source: "planned",
      available: false,
      preview: "concept",
      badge: "DITA",
    },
    {
      id: "newsletter",
      name: "Newsletter",
      description: "Multi-column newsletter with hero and article blocks.",
      category: "Newsletter",
      source: "planned",
      available: false,
      preview: "newsletter",
      badge: "New",
    },
    {
      id: "email-newsletter",
      name: "Email Newsletter",
      description: "Single-column email layout with header and sections.",
      category: "Newsletter",
      source: "planned",
      available: false,
      preview: "email",
      badge: "New",
    },
    {
      id: "linkedin",
      name: "LinkedIn Post",
      description: "Professional post with image and caption.",
      category: "Social Media",
      source: "planned",
      available: false,
      preview: "linkedin",
      badge: "Social",
    },
    {
      id: "instagram",
      name: "Instagram Post",
      description: "Square 1:1 visual-first post layout.",
      category: "Social Media",
      source: "planned",
      available: false,
      preview: "instagram",
      badge: "Social",
    },
  ];
}
